Consensys/linea-attestation-registry

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
> chore: As a Dev, I want a pre-commit hook to run some checks locally

- .github/PULL_REQUEST_TEMPLATE.md
> chore: As a Dev, I want a PR template to have a well formatted comment

- src/SchemaRegistry.sol
- test/SchemaRegistry.t.sol
> feat: As a User, I can discover all the Schemas

- src/ModuleRegistry.sol
- test/ModuleRegistry.t.sol
> feat: As a User, I can discover all the Modules

- .github/workflows/smart-contracts-test.yml
- test/ModuleRegistry.t.sol
> chore: As a Dev, I want the CI pipeline to fail if the smart contract coverage is not 100%

- src/ModuleRegistry.sol
- src/PortalRegistry.sol
- src/SchemaRegistry.sol
- src/types/Structs.sol
- test/AttestationRegistry.t.sol
- test/PortalRegistry.t.sol
- test/SchemaRegistry.t.sol
- test/mocks/PortalRegistryMock.sol
Adds some fixes on various places of the code
Fixes #100
> feat: Tweaks and Adjustments

- src/AttestationRegistry.sol
- src/portal/DefaultPortal.sol
- src/portal/EASPortal.sol
- test/AttestationRegistry.t.sol
- test/mocks/AttestationRegistryMock.sol
- test/mocks/SchemaRegistryMock.sol
> feat: added integrity check for attestation

- .github/workflows/smart-contracts-test.yml
- src/ModuleRegistry.sol
- src/PortalRegistry.sol
- src/SchemaRegistry.sol
- test/ModuleRegistry.t.sol
- test/PortalRegistry.t.sol
- test/SchemaRegistry.t.sol
- test/mocks/PortalRegistryMock.sol
> feat: added isIssuer check on module, schema and portal registries

- src/AttestationRegistry.sol
- src/interface/AbstractPortal.sol
- src/portal/DefaultPortal.sol
- test/AttestationRegistry.t.sol
- test/PortalRegistry.t.sol
- test/mocks/AttestationRegistryMock.sol
- test/portal/DefaultPortal.t.sol
Adds a way to bulk revoke attestations
Fixes #
> feat: As an attestation issuer, I want to revoke attestations that I've issued in bulk

- package.json
- pnpm-lock.yaml
* Updates npm dependencies
* Updates Foundry submodules
Fixes #127
> chore: Update all dependencies

- src/ModuleRegistry.sol
- src/example/CorrectModule.sol
- src/example/MsgSenderModule.sol
- src/interface/AbstractModule.sol
- src/interface/AbstractPortal.sol
- test/example/MsgSenderModule.t.sol
> fix: Modules shouldn't need an array of validation payloads + chore: Optimize modules for gas

- .gitmodules
- hardhat.config.ts
- src/ModuleRegistry.sol
- src/example/CorrectModule.sol
- src/example/EASPortal.sol
- src/example/MsgSenderModule.sol
- src/example/PayableModule.sol
- src/interface/AbstractModule.sol
- src/interface/AbstractPortal.sol
- src/portal/DefaultPortal.sol
- test/AttestationRegistry.t.sol
- test/ModuleRegistry.t.sol
- test/PortalRegistry.t.sol
- test/Router.t.sol
- test/SchemaRegistry.t.sol
- test/example/EASPortal.t.sol
- test/example/MsgSenderModule.t.sol
- test/example/PayableModule.t.sol
- test/mocks/ModuleRegistryMock.sol
- test/mocks/ValidPortalMock.sol
- test/portal/DefaultPortal.t.sol
- allows for payable module
- replaces attest hooks with onAttest
- removes unecessary check ModulePayloadMismatch in Portal
Fixes #183
> feature: As an Issuer, I want to benefit from a payable Module#183

- src/example/EASPortal.sol
- src/interface/AbstractPortal.sol
- src/portal/DefaultPortal.sol
- test/mocks/ValidPortalMock.sol
Implements the hooks inside the abstract Portal
#186
Fixes #
>  fix: add implementation of hooks in abstract portal

- src/AttestationRegistry.sol
- src/example/EASPortal.sol
- src/interface/AbstractPortal.sol
- src/portal/DefaultPortal.sol
- test/AttestationRegistry.t.sol
- test/example/EASPortal.t.sol
- test/mocks/AttestationRegistryMock.sol
- test/mocks/ValidPortalMock.sol
- test/portal/DefaultPortal.t.sol
> feat: add replace attestation feature

- .openzeppelin/unknown-59140.json
- .openzeppelin/unknown-59144.json
- README.md
- package.json
- script/upgrade/forceUpgradeEverything.ts
Fixes the way the "reimport" script is called
Upgrade the network file
> chore: minor fixes on the scripts

- .openzeppelin/sepolia.json
- hardhat.config.ts
Deploys the contracts stack on Sepolia
> feat: Deploy on Sepolia

- .eslintrc.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- sdk/.env.example
- sdk/README.md
- sdk/examples/AttestationFindOneById.ts
- sdk/index.html
- sdk/package.json
- sdk/src/AttestationRegistryWrapper.ts
- sdk/src/VeraxSdk.ts
- sdk/src/abi/AttestationRegistry.ts
- sdk/src/dataMapper/AttestationDataMapper.ts
- sdk/src/dataMapper/BaseDataMapper.ts
- sdk/src/dataMapper/ModuleDataMapper.ts
- sdk/src/dataMapper/PortalDataMapper.ts
- sdk/src/dataMapper/SchemaDataMapper.ts
- sdk/src/interface/Conf.ts
- sdk/tsconfig.json
- tsconfig.json
Adds the skeleton of the SDK
Fixes #202
> feat: As a Dev, I want to benefit from a skeleton of the SDK

- sdk/test/integration/Attestation.integration.test.ts
> fix: Fix SDK tests following new version of the subgraph

- contracts/test/AttestationReader.t.sol
> fix: Forge failing a test

- contracts/src/PortalRegistry.sol
- contracts/src/SchemaRegistry.sol
- contracts/test/PortalRegistry.t.sol
- contracts/test/SchemaRegistry.t.sol
- contracts/test/mocks/SchemaRegistryMock.sol
> fix: As an issuer, I can update another issuer's schema context

- contracts/src/examples/modules/MerkleProofModule.sol
- contracts/test/example/MerkleProofModule.t.sol
> Feat: As a user, I want to have an example merkle proof module

- contracts/src/examples/modules/ERC712Module.sol
- contracts/test/example/ERC712Module.t.sol
> feat: As a user, I want to have an example erc-712 module

- sdk/test/integration/Portal.integration.test.ts
Fixes the integration tests for the SDK (Portal)
> fix: SDK Portal integration tests

- sdk/README.md
- sdk/examples/attestation/attestationExamples.ts
- sdk/src/dataMapper/AttestationDataMapper.ts
- sdk/src/types/index.d.ts
> feat: As a user, I want to retrieve an attestation from the registry

- contracts/src/SchemaRegistry.sol
- contracts/test/SchemaRegistry.t.sol
- subgraph/abis/SchemaRegistry.json
- subgraph/src/schema-registry.ts
- subgraph/subgraph.goerli.yaml
- subgraph/subgraph.mainnet.yaml
> feat: As a user, I want the indexed Schemas to be updated when the context is updated

- contracts/src/AttestationRegistry.sol
- contracts/src/Common.sol
- contracts/src/ModuleRegistry.sol
- contracts/src/SchemaRegistry.sol
- contracts/src/examples/modules/MerkleProofModule.sol
- contracts/src/examples/portals/EASPortal.sol
- contracts/test/AttestationRegistry.t.sol
- contracts/test/example/MerkleProofModule.t.sol
- contracts/test/integration/AttestationRegistryMass.t.sol
Optimizes the gas cost of "for loops"
Fixes #349
> chore: Optimize the gas cost of "for loops"

- explorer/src/App.tsx
- sdk/package.json
- sdk/src/VeraxSdk.ts
Allows transactions to be sent from the frontend via the SDK
Fixes #341
> feat: As an Issuer, I want to attest from a frontend via the SDK

- contracts/src/PortalRegistry.sol
- contracts/test/PortalRegistry.t.sol
- subgraph/abis/PortalRegistry.json
- subgraph/schema.graphql
- subgraph/src/portal-registry.ts
- subgraph/tests/portal-registry.test.ts
> feat: As a user, I want the Verax Issuers to be indexed

- contracts/src/stdlib/IndexerModule.sol
- contracts/test/stdlib/IndexerModule.t.sol
Adds indexer querying by portal by subject
Fixes #
> feat: add index attestations by portal by subject

- README.md
Documents the use of the **Offchain Schema**
Fixes #378
> doc: Document the Offchain Schema used to attest off-chain payloads

- subgraph/schema.graphql
- subgraph/src/attestation-registry.ts
- subgraph/tests/attestation-registry.test.ts
> feat: as a user i want the version upgrade of the attestation registry to be indexed

- README.md
- explorer/src/App.tsx
- snap/README.md
> feat: Update URL of documentation

- subgraph/schema.graphql
- subgraph/src/attestation-registry.ts
- subgraph/tests/attestation-registry.test.ts
Reverts Consensys/linea-attestation-registry#385
> Revert "feat: as a user i want the version upgrade of the attestation registry to be indexed"

- package.json
- subgraph/schema.graphql
- subgraph/src/attestation-registry.ts
- subgraph/subgraph.goerli.yaml
- subgraph/subgraph.mainnet.yaml
- subgraph/tests/attestation-registry.test.ts
Indexes the version upgrade of the `AttestationRegistry`
Fixes #285
> feat: As a user, I want the version upgrade of the AttestationRegistry to be indexed

- sdk/package.json
- sdk/src/dataMapper/AttestationDataMapper.ts
- sdk/src/types/index.d.ts
- sdk/src/utils/abiCoder.ts
- sdk/test/integration/Attestation.integration.test.ts
> feat: As a developer, I want the SDK to decode all attestations on the fly

- sdk/src/VeraxSdk.ts
- sdk/src/dataMapper/AttestationDataMapper.ts
- sdk/src/dataMapper/BaseDataMapper.ts
- sdk/src/dataMapper/ModuleDataMapper.ts
- sdk/src/dataMapper/PortalDataMapper.ts
- sdk/src/dataMapper/SchemaDataMapper.ts
- sdk/src/utils/transactionSender.ts
> fix: Webapps fail to load when the browser doesn't have MetaMask installed

- website/src/components/Footer.tsx
Removes link to Discourse from footer until after POH wave
> chore: Removed link to forum

- sdk/examples/attestation/attestationExamples.ts
- sdk/src/dataMapper/AttestationDataMapper.ts
- sdk/src/types/index.ts
- sdk/src/utils/constants.ts
- sdk/src/utils/ipfsClient.ts
> feat: As an Issuer, I want to decode off-chain attestations through the SDK

- sdk/src/VeraxSdk.ts
This script adds arbitrum testnet and mainnet to the SDK
Fixes #
> chore: add arbitrum SDK config

- sdk/README.md
- sdk/package.json
Releases the `v1.0.0` of the SDK
> chore: Release SDK v1.0.0

- explorer/package.json
- pnpm-lock.yaml
- sdk/package.json
- website/package.json
- website/src/components/Footer.tsx
Adds a Lens follow button on the website landing page
> feat: Add a Lens follow button on the landing page

- website/package.json
- website/src/App.css
- website/src/App.tsx
- website/src/components/Navbar.tsx
- website/src/index.css
- website/src/pages/Poh.css
- website/src/pages/Poh.tsx
> feat: As a User, I want to check my POH status

- explorer/src/assets/locales/en/en.json
- explorer/src/components/Back/index.tsx
- explorer/src/components/NotFoundPage/utils.ts
- explorer/src/hooks/useHandleSearch.ts
- explorer/src/interfaces/swr/enum.ts
- explorer/src/pages/Attestation/components/AttestationSchemaCard/index.tsx
- explorer/src/pages/Attestation/components/RelatedAttestations/index.tsx
- explorer/src/pages/Attestation/index.tsx
- explorer/src/pages/Home/components/Issuer/index.tsx
- explorer/src/pages/Issuer/components/Portals/index.tsx
- explorer/src/pages/Issuer/index.tsx
- explorer/src/pages/Module/index.tsx
- explorer/src/pages/Portal/components/PortalLoadingSkeleton/index.tsx
- explorer/src/pages/Portal/components/PortalModules/index.tsx
- explorer/src/pages/Portal/index.tsx
- explorer/src/pages/Schema/index.tsx
- explorer/src/providers/network-provider/index.tsx
- explorer/src/utils/stringUtils.ts
https://github.com/Consensys/linea-attestation-registry/issues/473
> feat: As a user, I want to be able to see the portal page on the Explorer

- website/src/pages/Poh.css
- website/src/pages/Poh.tsx
Adds some explanation to the POH page
> fix: Change POH page wording

- website/src/App.tsx
- website/src/pages/Home.tsx
- website/src/pages/Poh.tsx
- website/src/pages/SDKDemo.tsx
Add a title to the website pages
> feat: Add a title to the website pages

- website/src/pages/Poh.tsx
Replaces the POH status emojis by real icons for maximum compatibility across OSs and browsers
> fix: Display POH status as icons

- website/src/pages/Poh.tsx
Changes the link to Nomis landing page
> fix: Change Nomis link

- explorer/src/components/BurgerMenu/index.tsx
- explorer/src/components/LightDarkModeSwitcher/index.tsx
- explorer/src/components/NavigationList/index.tsx
- explorer/src/pages/Layout/index.tsx
- Fixed theme behaviour on adaptive screens
- Change burgers menu 100vh to 100dvh
> fix: made theme fixes after QA review

- explorer/package.json
- explorer/vite.config.ts
- pnpm-lock.yaml
- website/vite.config.ts
Adds a Google Analytics tag to the Explorer
> feat: Add a Google Analytics tag to the explorer

- explorer/package.json
- pnpm-lock.yaml
- sdk/package.json
- website/package.json
Updates the SDK version to fix the issue with the testnet explorer
> fix: Testnet explorer and website

- sdk/src/utils/abiCoder.ts
- sdk/test/integration/Attestation.integration.test.ts
Decodes all types of Attestations
Fixes #504
> feat: As a User, I want fully decoded Attestations payloads

- explorer/package.json
- explorer/src/pages/Attestation/components/AttestationData/utils.ts
- pnpm-lock.yaml
- sdk/package.json
- website/package.json
feat: Fully decode the attestation on the explorer
Updates the SDK for the website and the explorer
Which decodes all the attestations at the explorer level
> chore: Update the SDK for website & explorer

- explorer/src/assets/locales/en/en.json
- explorer/src/components/Pagination/PerPageSelector/index.tsx
- explorer/src/components/Pagination/index.tsx
- explorer/src/enums/queryParams.ts
- explorer/src/pages/Attestations/index.tsx
- explorer/src/pages/Modules/index.tsx
- explorer/src/pages/Schemas/index.tsx
- explorer/src/utils/paginationUtils.ts
items per screen selector implemented 
Fixes #512
> Feat: As a User, I want to see more than 10 items per screen

- explorer/src/assets/issuers/automata.svg
- explorer/src/pages/Home/data.tsx
1. Update the pattern id of Automata Network's logo, otherwise there is a conflict with logos of other issuers
2. Update issuer address of Automata Network
Fixes #
> Update issuer data of Automata Network

- website/src/components/CreatePortal.tsx
Fixes an issue with the tutorial blocked at step 3
> fix: Tutorial step 3 is locked

- website/index.html
Updates website to redirect to new website at https://www.ver.ax
n/a
- [*] New feature
> Updated Verax homepage to redirect to www.ver.ax

- README.md
Updates the Readme file following some feedback from the builders
> doc: Update the README file

- sdk/examples/utils/countUniqueSubjects.ts
- sdk/examples/utils/getAllAttestations.ts
> fix: Some attestations are downloaded twice via the "getAllAttestations" script

- .github/workflows/tutorial-deploy-preview.yml
- .github/workflows/tutorial-deploy-prod.yml
> feat: Deploy tutorial

- sdk/package.json
- sdk/src/dataMapper/PortalDataMapper.ts
Adds an optional parameter to the SDK `attest` method, to pass a value when attesting.
Fixes #583
> feat: As an Issuer, I want to be able to issue payable attestations via the SDK

- .husky/pre-commit
Only run tests on contracts on the pre-commit hook
> chore: Reduce number of tests run on commit

- .github/workflows/smart-contracts.yml
Fixes the contracts CI pipeline
> fix: Contracts pipeline

- sdk/package.json
- sdk/src/VeraxSdk.ts
> chore: As a developer, I want to use the SDKMode from the SDK

- explorer/package.json
- pnpm-lock.yaml
- sdk/package.json
- sdk/src/VeraxSdk.ts
- subgraph/src/attestation-registry.ts
> fix: Some attestation payloads caused the subgraph to fail while indexing

- explorer/src/constants/index.ts
Fix a broken link for the Linea Sepolia chain explorer
> fix: Linea Sepolia explorer URL

- explorer/package.json
- pnpm-lock.yaml
Updates the SDK dependency for the Explorer
> chore: Update the SDK for the Explorer

- .github/CODEOWNERS
- .github/workflows/explorer-deploy-prod.yml
- .github/workflows/releaser.yml
Updates the code owners and authorized deployers
> chore: Update code owners

- contracts/src/PortalRegistry.sol
Improved the code avoiding loop when match is found.
Fixes #654
> fix(contracts): Improve the Portal revocation function

- README.md
The bottom part of the Readme was hidden because of a missing tag
> fix: End of the Readme is hidden

- explorer/src/assets/issuers/index-network-black.svg
- explorer/src/assets/issuers/index-network.svg
- explorer/src/pages/Home/data.tsx
Adds Index Network to the ecosystem dashboard on the Explorer
Fixes #664
> chore(explorer): Add Index Network to ecosystem dashboard

- explorer/src/pages/Schema/components/RecentAttestations/index.tsx
This PR fixes the sorting direction with consistency.
Fixes #686
> fix(explorer): As a user, I want to have a consistent default sorting logic across all the pages in the explorer

- contracts/src/ModuleRegistry.sol
- contracts/src/abstracts/AbstractModuleV2.sol
- contracts/src/abstracts/AbstractPortal.sol
- contracts/src/examples/modules/ERC712ModuleV2.sol
- contracts/src/examples/modules/MerkleProofModuleV2.sol
- contracts/src/stdlib/ECDSAModuleV2.sol
- contracts/src/stdlib/ERC1271ModuleV2.sol
- contracts/src/stdlib/FeeModuleV2.sol
- contracts/src/stdlib/IndexerModuleV2.sol
- contracts/src/stdlib/IssuersModuleV2.sol
- contracts/src/stdlib/SchemaModuleV2.sol
- contracts/src/stdlib/SenderModuleV2.sol
- contracts/src/types/Enums.sol
- contracts/test/DefaultPortal.t.sol
- contracts/test/ModuleRegistry.t.sol
- contracts/test/examples/modules/ERC712ModuleV2.t.sol
- contracts/test/examples/modules/MerkleProofModuleV2.t.sol
- contracts/test/mocks/CorrectModuleV2Mock.sol
- contracts/test/mocks/ModuleRegistryMock.sol
- contracts/test/stdlib/ECDSAModuleV2.t.sol
- contracts/test/stdlib/ERC1271ModuleV2.t.sol
- contracts/test/stdlib/FeeModuleV2.t.sol
- contracts/test/stdlib/IndexerModuleV2.t.sol
- contracts/test/stdlib/IssuersModuleV2.t.sol
- contracts/test/stdlib/SchemaModuleV2.t.sol
- contracts/test/stdlib/SenderModuleV2.t.sol
It adds operation type to distinguish between attest and replace workflows
Fixes #648
> feat(contracts): As an Issuer, I want to have dedicated logic on ”attest” and “replace” workflows

- explorer/src/components/Title/index.tsx
- explorer/src/pages/Subject/index.tsx
Adds a title to the Subject Page
Adds a copyable address as subtitle
Fixes #815
> feat(explorer): As a user, I want the Subject Page title to be explicit

- .github/CODEOWNERS
Updates the code owners list to better reflect the current state of the project
> chore(repo): Update the code owners

- contracts/src/abstracts/AbstractPortal.sol
- contracts/src/abstracts/AbstractPortalV2.sol
Optimizes the ordering of hooks in the Abstract Portals to make them more readable
Fixes #829
> chore(contracts): Inconsistent ordering of functions in AbstractPortal

- contracts/src/AttestationRegistry.sol
Improve the NatSpec comment on the `attest` method
Fixes #805
> chore(contracts): Warning on creating expired Attestation

- explorer/README.md
> doc(explorer): Improve the deployment documentation for the Explorer

- sdk/README.md
> doc(explorer): Improve the deployment documentation for the SDK

- contracts/src/examples/portals/EASPortal.sol
> fix(contracts): Incorrect Attestation ID in Relationship Attestations

- contracts/src/AttestationReader.sol
- contracts/src/AttestationRegistry.sol
- contracts/src/examples/portals/NFTPortal.sol
- contracts/src/stdlib/IssuersModuleV2.sol
- contracts/test/examples/portals/NFTPortal.t.sol
> bugfix(contracts): Ambiguity in `subject` Field of AttestationPayload

- contracts/src/examples/portals/NFTPortal.sol
- contracts/src/examples/portals/PausablePortal.sol
> chore(contracts): Remove empty withdraw function

- contracts/src/PortalRegistry.sol
> chore(contracts): State-Changing `removeIssuer` Succeed and Emit an Event Even When No State Change Occurs

- contracts/src/abstracts/AbstractPortalV2.sol
> chore(contracts): Lack of Documentation for Portal Creators About Potential Accounting Problem With Modules
