Consensys/linea-attestation-registry

.github/CODEOWNERS

Add @orbmis and @0xEillo as code owners

chore: Add two code owners

---

remappings.txt
src/AttestationRegistry.sol
src/PortalRegistry.sol
src/interface/AbstractPortal.sol
src/portal/DefaultPortal.sol
src/types/Structs.sol
test/AttestationRegistry.t.sol
test/PortalRegistry.t.sol
test/mocks/AttestationRegistryMock.sol
test/mocks/PortalRegistryMock.sol
test/portal/DefaultPortal.t.sol

Adds a `revoke` method to revoke (and potentially replace) an attestation
Fixes #31

feat: As an Attestation Issuer, I want to revoke an Attestation I issued

---

src/AttestationRegistry.sol
src/PortalRegistry.sol
src/interface/AbstractPortal.sol
src/portal/DefaultPortal.sol
src/types/Structs.sol
test/PortalRegistry.t.sol
test/mocks/AttestationRegistryMock.sol
test/mocks/ModuleRegistryMock.sol
test/portal/DefaultPortal.t.sol
test/portal/EASPortal.t.sol

Moves Portal logic for the attest function into internal functions in the abstract contract to enforce correct Portal Behaviours.
Adds lifecycle hooks to Portals.
Changes attestationId to uint256 that increments.
Removes attestationId from AttestationPayload.
Removes version from AttestationPayload.
Fixes #96

feat: add lifecycle hooks to abstract contract

---

src/interface/AbstractPortal.sol
src/portal/EASPortal.sol
test/PortalRegistry.t.sol
test/mocks/AttestationRegistryMock.sol
test/mocks/ModuleRegistryMock.sol
test/portal/DefaultPortal.t.sol
test/portal/EASPortal.t.sol

This PR is a different implementation of the EASPortal. In this implementation, we maintain use the AbstractPortal contract instead of creating a new EASAbstractPortal. This will allow us to register the EASPortal to the PortalRegistry and avoids custom code for EAS
Fixes #114

feat: As a Dev, I want the EASPortal to be based on the AbstractPortal

---

script/deployDefaultPortal.ts
script/deployEASPortal.ts
script/deployEverything.ts
src/AttestationRegistry.sol
src/interface/AbstractPortal.sol
test/AttestationRegistry.t.sol
test/mocks/AttestationRegistryMock.sol

Removes the hash to generate the `Attestation`'s ID
Fixes #118

feat: As a user, I want the Attestation ID to be more predictable

---

src/ModuleRegistry.sol
src/example/CorrectModule.sol
src/example/MsgSenderModule.sol
src/interface/AbstractModule.sol
src/interface/AbstractPortal.sol
src/portal/EASPortal.sol
test/ModuleRegistry.t.sol
test/example/MsgSenderModule.t.sol
test/mocks/ModuleRegistryMock.sol

Passes the `attestationPayload` to modules so that they can validate the attestation data
Fixes #134

feat: Portals should pass attestationPayload to modules as well as validationPayload

---

src/AttestationRegistry.sol
src/ModuleRegistry.sol
src/PortalRegistry.sol
src/example/EASPortal.sol
src/interface/AbstractPortal.sol
src/portal/DefaultPortal.sol
src/types/Structs.sol
test/AttestationRegistry.t.sol
test/ModuleRegistry.t.sol
test/PortalRegistry.t.sol
test/Router.t.sol
test/example/EASPortal.t.sol
test/example/MsgSenderModule.t.sol
test/mocks/AttestationRegistryMock.sol
test/mocks/ModuleRegistryMock.sol
test/mocks/PortalRegistryMock.sol
test/portal/DefaultPortal.t.sol

Optimizes various points to get cheaper attestation issuance:
- Smaller events data
- Less events
- No useless returned value
- Timestamp as `uint64`
- Better packed struct definition
Fixes #145

feat: Optimize the issuance of attestations

---

src/AttestationRegistry.sol
test/AttestationRegistry.t.sol
test/integration/AttestationRegistryMass.t.sol

* Adds a `massImport` method to create cheap attestations in batch
* Adds some "integration tests" to compare the gas cost for issuing attestations via `massImport` and `bulkAttest`
Fixes #156

feat: Investigate mass import mechanism

---

src/example/MsgSenderModule.sol
test/example/MsgSenderModule.t.sol

Removes the "initializable" behaviour of the `MsgSenderModule`, therefore making it not upgradeable.
Fixes #178

feat: As an Issuer, I want my module(s) not to be upgradeable

---

src/PortalRegistry.sol
src/example/EASPortal.sol
src/interface/AbstractPortal.sol
src/portal/DefaultPortal.sol
test/PortalRegistry.t.sol
test/example/EASPortal.t.sol
test/integration/AttestationRegistryMass.t.sol
test/mocks/ValidPortalMock.sol
test/portal/DefaultPortal.t.sol

Prevents the portals from being initializable or upgradeable
Fixes #198

fix: Portal should not be initializable/upgradeable

---

src/ModuleRegistry.sol

Fixes an issue in the bulk run module feature: we were looping on modules instead of attestations payloads!
Fixes #217

fix: When bulk running modules, loop over attestations payloads and not modules

---

src/AttestationRegistry.sol
test/AttestationRegistry.t.sol

As the `massImport` method doesn't emit an event on attestation creation, it can't be processed by an indexer. This PR adds this event.
Fixes #215

fix: The mass import feature should emit an AttestationRegistered event for each attestation created

---

src/example/EASPortal.sol
src/example/NFTPortal.sol
src/interface/AbstractPortal.sol
test/example/EASPortal.t.sol
test/portal/DefaultPortal.t.sol

- Adds msg.value and attester to onAttest and onReplace hooks. This allows for custom portal logic on attestations with fees as well as information on the attester field which is not in the AttestationPayload struct
- Makes _attester() function visibility internal
- Removes "payable" modifier from bulkAttest and bulkReplace which cannot handle msg.value
Fixes #

feat: add msg.value and _attester() to hooks

---

src/AttestationRegistry.sol
src/ModuleRegistry.sol
src/PortalRegistry.sol
src/Router.sol
src/SchemaRegistry.sol
src/example/CorrectModule.sol
src/example/EASPortal.sol
src/example/IncorrectModule.sol
src/example/MsgSenderModule.sol
src/example/PayableModule.sol
src/interface/AbstractModule.sol
src/interface/AbstractPortal.sol
src/interface/IRouter.sol
src/portal/DefaultPortal.sol
test/ModuleRegistry.t.sol
test/PortalRegistry.t.sol
test/Router.t.sol
test/SchemaRegistry.t.sol
test/example/EASPortal.t.sol
test/example/MsgSenderModule.t.sol
test/mocks/AttestationRegistryMock.sol
test/mocks/ModuleRegistryMock.sol
test/mocks/PortalRegistryMock.sol
test/portal/DefaultPortal.t.sol

- Unifies tests names
- Adds a lot of NatSpec comments on smart contracts
- Eliminates most of the linting warnings
Fixes #94

chore: Cleanup and improvements

---

src/AttestationRegistry.sol
test/AttestationRegistry.t.sol

feat: as an attestation consumer, I want to be able to check if an address has an attestation using the ERC-1155 owner method

---

src/AttestationRegistry.sol
test/AttestationRegistry.t.sol

Reverts Consensys/linea-attestation-registry#227

Revert "feat: as an attestation consumer, I want to be able to check if an address has an attestation using the ERC-1155 owner method"

---

subgraph/schema.graphql
subgraph/src/attestation-registry.ts
subgraph/src/module-registry.ts
subgraph/src/portal-registry.ts
subgraph/src/schema-registry.ts

Adds a `Counter` entity to the subgraph to follow the number of Attestation, Modules, Portals and Schemas
Fixes #235

feat: As a User, I want to check the number of Attestation, Modules, Portals and Schemas from the subgraph

---

pnpm-lock.yaml
sdk/jest.config.js
sdk/package.json
sdk/test/dataMapper/AttestationDataMapper.test.ts

chore: Add test framework

---

sdk/examples/attestation/attestationExamples.ts
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/src/dataMapper/BaseDataMapper.ts
sdk/src/types/index.d.ts
sdk/src/utils/constants.ts
sdk/test/dataMapper/AttestationDataMapper.test.ts

Adds a method to get all attestations related to a given attestation, via the SDK
Fixes #174

feat: As user, I want to use the SDK to return all attestations that have a relationship to a specific attestation

---

sdk/examples/portal/portalExamples.ts
sdk/src/dataMapper/BaseDataMapper.ts
sdk/src/dataMapper/PortalDataMapper.ts

feat: added revoke and simulateRevoke

---

sdk/README.md
sdk/examples/attestation/attestationExamples.ts
sdk/examples/attestation/index.ts
sdk/examples/module/index.ts
sdk/examples/module/moduleExamples.ts
sdk/examples/portal/index.ts
sdk/examples/portal/portalExamples.ts
sdk/examples/schema/index.ts
sdk/examples/schema/schemaExamples.ts

chore: accepting the param values for examples

---

README.md

chore: Better README

---

contracts/src/examples/modules/ECDSAModule.sol
contracts/test/example/ECDSAModule.t.sol

feat: As a user, I want to have an example `ecrecover` module

---

.github/workflows/subgraph.yml
.gitignore
pnpm-lock.yaml
subgraph/package.json
subgraph/src/module-registry.ts
subgraph/src/portal-registry.ts
subgraph/src/schema-registry.ts
subgraph/tests/attestation-registry.test.ts
subgraph/tests/module-registry.test.ts
subgraph/tests/portal-registry.test.ts
subgraph/tests/schema-registry.test.ts
subgraph/tsconfig.json

Add unit tests for the subgraph
Fixes #225

chore: Add unit test to the subgraph

---

sdk/README.md
sdk/examples/attestation/attestationExamples.ts
sdk/examples/portal/portalExamples.ts
sdk/src/abi/AttestationRegistry.ts
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/src/dataMapper/PortalDataMapper.ts
sdk/src/dataMapper/UtilsDataMapper.ts
sdk/src/utils/errorHandler.ts
sdk/src/utils/simulationErrorHandler.ts
sdk/src/utils/transactionSender.ts

feat: As a user, I want to be able to call any method on the `AttestationRegistry` via the SDK

---

contracts/src/examples/portals/NFTPortal.sol

fix: The NFTPortal should declare that the IPortal interface is implemented

---

sdk/README.md

Updates the SDK documentation
Fixes #296

chore: Update the SDK documentation to reflect its finalized organization

---

.gitignore
README.md
sdk/.npmignore
sdk/LICENSE
sdk/package.json
sdk/src/VeraxSdk.ts
sdk/tsconfig.cjs.json
sdk/tsconfig.esm.json
sdk/tsconfig.json

- Builds the SDK as a package
- Publishes it onto the NPM registry
Fixes #273

chore: Build and Publish the SDK as an NPM package

---

subgraph/src/attestation-registry.ts
subgraph/tests/attestation-registry.test.ts

feat: As a user, I want the indexed Attestations to be updated on revocation and all other change events

---

package.json
sdk/test/integration/Attestation.integration.test.ts
subgraph/schema.graphql
subgraph/src/attestation-registry.ts
subgraph/tests/attestation-registry.test.ts

Decodes the attestation subject if it looks like an encoded address
Fixes #312

feat: As an Issuer, I want to use the subject field as an ETH address or an encoded ETH address

---

contracts/.openzeppelin/unknown-59140.json
contracts/.openzeppelin/unknown-59144.json

Updates the network files with the latest (v5) upgrade of the smart contracts

chore: Release Verax v5 on Linea testnet and mainnet

---

.github/workflows/smart-contracts.yml

Makes the upgradeability check on contracts pass when no change was made on the `contracts` folder

chore: Only run the upgradeability checks if the contracts folder was changed

---

.github/workflows/smart-contracts.yml
contracts/.openzeppelin/arbitrum-goerli.json
contracts/.openzeppelin/arbitrum-one.json
contracts/.openzeppelin/unknown-59140.json
contracts/.openzeppelin/unknown-59144.json
contracts/package.json

Upgrades Verax contracts to v6 on Linea testnet and mainnet

chore: Deploy Verax v6 on Linea

---

.github/CODEOWNERS

Adds Hapi as codeowners of the explorer package

chore: Add Hapi as codeowners

---

explorer/src/routes/index.tsx

fix: Use a HashRouter to make the explorer work on Netlify

---

explorer/src/pages/Attestation/components/AttestationData/index.tsx
explorer/src/pages/Attestation/components/AttestationData/utils.ts

Uses the attestation payload decoded at the SDK level to display the detail of an attestation
Fixes #469

fix: On the Explorer, the attested payload is not the most explicit we can get

---

sdk/package.json
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/test/integration/Attestation.integration.test.ts

Converts the dates fields back to `number` (instead of default `string`)
Fixes #447

fix: Fix the type of the date fields in Attestation at the SDK level

---

sdk/examples/utils/countUniqueSubjects.ts
sdk/examples/utils/getAllAttestations.ts

1. Adds a script to get all attestations and save all the subjects in files
2. Adds a script to count unique subjects
Fixes #475

feat: As a user, I want to count unique attested subjects

---

explorer/src/pages/Schema/components/RecentAttestations/index.tsx

Portal's and schema's columns visibility in schema's related attestations table fixed

fix: made portal and schema columns visible in schema's related attestations

---

sdk/src/VeraxSdk.ts

Fixes the issue with the missing Linea testnet subgraph by replacing it by a new one

fix: Use another Linea Testnet subgraph

---

.github/workflows/explorer-build.yml
.github/workflows/explorer-deploy-preview.yml
.github/workflows/explorer-deploy-prod.yml
.github/workflows/releaser.yml
.github/workflows/smart-contracts.yml
.github/workflows/subgraph.yml
.github/workflows/website-build.yml
explorer/README.md

Adds the ability to deploy the Explorer in production mode
Skips the deployment of a preview explorer when the changes are not on the Explorer package

feat: Deploy the Explorer in production mode

---

.github/workflows/explorer-deploy-preview.yml
.github/workflows/explorer-deploy-prod.yml
explorer/package.json
explorer/src/routes/index.tsx

Switches the Explorer from `HashRouter` to `BrowserRouter` to have cleaner URLs
Fixes #464

chore: When the Explorer is deployed in production, remove the `HashRouter`

---

sdk/examples/attestation/attestationExamples.ts
sdk/examples/attestation/index.ts
sdk/examples/module/index.ts
sdk/examples/module/moduleExamples.ts
sdk/examples/portal/index.ts
sdk/examples/portal/portalExamples.ts
sdk/examples/schema/index.ts
sdk/examples/schema/schemaExamples.ts
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/src/dataMapper/ModuleDataMapper.ts
sdk/src/dataMapper/PortalDataMapper.ts
sdk/src/dataMapper/SchemaDataMapper.ts
sdk/src/utils/transactionSender.ts

feat: As a user, I want the SDK to check the transaction was validated before finishing a process

---

website/src/components/CreatePortal.tsx
website/src/components/CreateSchema.tsx
website/src/components/IssueAttestation.tsx
website/src/pages/Tutorials.tsx

feat: As a developer, I want to see an end-to-end hello-world tutorial

---

explorer/package.json
pnpm-lock.yaml
sdk/doc/cli-examples.md
sdk/examples/attestation/attestationExamples.ts
sdk/package.json
sdk/src/dataMapper/AttestationDataMapper.ts
tutorial/package.json

When getting one or multiple attestation(s), the calls to fetch the Schema are now made to the subgraph instead of the chain. This reduces the number of RPC calls to 0 for such operations.
Fixes #579

fix: Reduce the number of RPC calls when fetching attestations

---

contracts/src/ModuleRegistry.sol
contracts/src/abstracts/AbstractModuleV2.sol
contracts/src/abstracts/AbstractPortal.sol
contracts/src/examples/modules/ERC712ModuleV2.sol
contracts/src/examples/modules/MerkleProofModuleV2.sol
contracts/src/stdlib/ECDSAModuleV2.sol
contracts/src/stdlib/ERC1271ModuleV2.sol
contracts/src/stdlib/FeeModuleV2.sol
contracts/src/stdlib/IndexerModuleV2.sol
contracts/src/stdlib/IssuersModuleV2.sol
contracts/src/stdlib/SchemaModuleV2.sol
contracts/src/stdlib/SenderModuleV2.sol
contracts/test/ModuleRegistry.t.sol
contracts/test/examples/modules/ERC712ModuleV2.t.sol
contracts/test/examples/modules/MerkleProofModuleV2.t.sol
contracts/test/integration/IssuersPortalV2.t.sol
contracts/test/mocks/CorrectModuleV2Mock.sol
contracts/test/stdlib/ECDSAModuleV2.t.sol
contracts/test/stdlib/ERC1271ModuleV2.t.sol
contracts/test/stdlib/FeeModuleV2.t.sol
contracts/test/stdlib/IndexerModuleV2.t.sol
contracts/test/stdlib/IssuersModuleV2.t.sol
contracts/test/stdlib/SchemaModuleV2.t.sol
contracts/test/stdlib/SenderModuleV2.t.sol

Introduces a "Modules V2" feature, for more flexibility and more use cases
* Gas cost for the integration test `IssuersPortal` V1 = 694065
* Gas cost for the integration test `IssuersPortal` V2 = 694780
=> Increased by 0.1% (715 gas)
Fixes #574

feat: Introduce Modules V2 with more flexibility

---

.gitignore
contracts/package.json
contracts/postpack.sh
contracts/prepack.sh
pnpm-lock.yaml

Deploys the smart contracts to npm for anyone to use them easily
Depends on #592 to be merged first
Fixes #591

feat: As a developer i want to import the Verax contracts via npm in my project

---

sdk/package.json
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/src/dataMapper/BaseDataMapper.ts
sdk/src/dataMapper/ModuleDataMapper.ts
sdk/src/dataMapper/PortalDataMapper.ts
sdk/src/dataMapper/SchemaDataMapper.ts
sdk/src/dataMapper/UtilsDataMapper.ts
sdk/src/types/index.ts
sdk/src/utils/abiCoder.ts
sdk/src/utils/constants.ts
sdk/src/utils/errorHandler.ts
sdk/src/utils/graphClientHelper.ts
sdk/src/utils/ipfsClient.ts
sdk/src/utils/transactionSender.ts

- Removes all `console.log` and `console.error` from the SDK
- Fixes some typing issues
Fixes #622

chore: Remove logs from the SDK

---

explorer/src/components/NotFoundPage/index.tsx
explorer/src/constants/columns/attestation.tsx
explorer/src/pages/Attestation/components/AttestationInfo/index.tsx
explorer/src/pages/Attestation/components/RelatedAttestations/index.tsx

Attestation IDs were wrongly converted to a huge number on some networks
Fixes #624

fix: Attestation IDs are rendered incorrectly on Verax Explorer on Base mainnet

---

contracts/src/abstracts/AbstractPortal.sol
contracts/src/examples/portals/EASPortal.sol
contracts/src/examples/portals/NFTPortal.sol

Adds a warning on the `AbstractPortal` and the example Portals to make sure the `withdraw` is implemented when needed.
This warning can also be found in [the documentation](https://docs.ver.ax/verax-documentation/developer-guides/for-attestation-issuers/create-a-portal).
Fixes #639

chore(contracts): Add a warning on the `withdraw` function not being implemented

---

contracts/src/ModuleRegistry.sol
contracts/src/abstracts/AbstractPortal.sol
contracts/src/examples/portals/EASPortal.sol

Adds a warning on the `AbstractPortal`, the `ModuleRegistry` and the example Portals to warn about an edge case with the `bulkRunModules` function.
This warning can also be found in [the documentation](https://docs.ver.ax/verax-documentation/developer-guides/for-attestation-issuers/bulk-create-attestations).
Fixes #640

chore(contracts): Add a warning on the `bulkRunModules` being exposed to not incremented attestation ID

---

sdk/examples/attestation/index.ts
sdk/examples/module/index.ts
sdk/examples/portal/index.ts
sdk/examples/schema/index.ts
sdk/examples/utils/decode.ts
sdk/examples/utils/encode.ts
sdk/examples/utils/getAttestationIdCounter.ts
sdk/examples/utils/getModulesNumber.ts
sdk/examples/utils/getPortalsCount.ts
sdk/examples/utils/getRelatedAttestation.ts
sdk/examples/utils/getSchemasNumber.ts
sdk/examples/utils/getVersionNumber.ts

Updates the default network in SDK examples to Linea Sepolia
Also corrects the Schema examples class in schema index file
Fixes #645

chore(sdk): As a user, I want to use Linea Sepolia as a default network in examples

---

.github/workflows/smart-contracts.yml
contracts/README.md
contracts/src/PortalRegistry.sol
contracts/src/SchemaRegistry.sol
contracts/test/PortalRegistry.t.sol
contracts/test/SchemaRegistry.t.sol
contracts/test/mocks/SchemaRegistryMock.sol

Removed the call to updateMatchingSchemaIssuers in remove issuers
Added two separate methods below 
1. updateSchemaIssuerWithPortalOwner
2. bulkUpdateSchemasIssuersWithPortalOwner
Fixes #653

chore(contracts): Improve the removal of Issuers

---

.github/workflows/smart-contracts.yml

When no change was done on the contracts, stop checking their code coverage
Fixes #675

chore(ci): Don't check contracts coverage when no change was done

---

explorer/src/constants/columns/attestation.tsx
explorer/src/constants/columns/module.tsx
explorer/src/constants/columns/portal.tsx
explorer/src/constants/index.ts
explorer/src/pages/Attestation/components/AttestationInfo/index.tsx
explorer/src/pages/Attestations/index.tsx
explorer/src/pages/Module/index.tsx
explorer/src/pages/Modules/index.tsx
explorer/src/pages/MyAttestations/index.tsx
explorer/src/pages/Portal/components/PortalModules/index.tsx
explorer/src/pages/Schema/components/RecentAttestations/index.tsx
explorer/src/pages/Schemas/index.tsx
explorer/src/pages/Search/components/SearchAttestationsReceived/index.tsx
explorer/src/pages/Search/components/SearchModules/index.tsx
explorer/src/pages/Search/components/SearchPortals/index.tsx
explorer/src/providers/network-provider/index.tsx
explorer/src/utils/index.ts

This PR manage to take blockexplorer links automatically from wagmi config, no need to add new chain's block explorer links to any obj, if only there is some custom chain. 
Fixed switching the chain when the user is connected to explorer via Metamask
Fixes #

fix(explorer): Block explorer links

---

explorer/src/pages/Attestations/index.tsx

This PR changes the way results are loaded on pagination. It uses id where clause rather than skip parameter.
In this way it fixes the limitation of skip parameter being not returning results for large number of pages.
Fixes #685

fix(explorer): Unable to go back far in the Attestations history

---

explorer/src/config/index.tsx
explorer/src/interfaces/config/index.ts
explorer/src/pages/Attestations/index.tsx
explorer/src/utils/attestationIdUtils.ts

- Displays the latest Attestation which was hidden
- Displays Attestations on networks other than Linea
Fixes #697

fix(explorer): The Explorer doesn't correctly display the list of Attestations on all networks

---

README.md
explorer/package.json
explorer/src/constants/columns/attestation.tsx
explorer/src/constants/index.ts
explorer/src/pages/Attestation/components/AttestationInfo/index.tsx
explorer/src/pages/Attestation/index.tsx
explorer/src/pages/Attestations/components/SWRCell/index.tsx
explorer/src/pages/Attestations/index.tsx
explorer/src/pages/MyAttestations/index.tsx
explorer/src/pages/Schema/components/RecentAttestations/index.tsx
explorer/src/pages/Search/components/SearchAttestationsReceived/index.tsx
explorer/src/pages/Search/components/SearchAttestationsReceived/loadAttestationReceivedList.ts
pnpm-lock.yaml
sdk/.graphclient/index.ts
sdk/.graphclient/schema.graphql
sdk/.graphclient/sources/linea-attestation-registry/introspectionSchema.ts
sdk/.graphclient/sources/linea-attestation-registry/schema.graphql
sdk/.graphclient/sources/linea-attestation-registry/types.ts
sdk/.graphclientrc.yml
sdk/package.json
sdk/src/VeraxSdk.ts
sdk/src/dataMapper/AttestationDataMapper.ts
sdk/src/types/index.ts
sdk/test/integration/Attestation.integration.test.ts

1. Migrates the SDK from subgraph v1 to subgraph v2
2. Upgrades the SDK for the explorer
Consequences:
- Breaking changes with a new `Attestation` type
- Way less calls to the subgraph to get Attestations (from up to 301 calls to display 100 Attestations to only 1 call)
Remaining work:
Fixes #585

feat(sdk): As a Developer, I want the SDK to be compatible with the new version of the subgraph

---

explorer/src/utils/searchUtils.ts

Fixes the search feature when looking for an address as a subject
Fixes #709

fix(explorer): Unable to search Attestations by subject

---

contracts/.openzeppelin/unknown-59141.json
contracts/package.json

- Upgrades the core smart contracts to V8
- Publishes a new version of the Verax contracts to [npm](https://www.npmjs.com/package/@verax-attestation-registry/verax-contracts)
Fixes #706

chore(contracts): Upgrade Verax to V8

---

contracts/src/examples/portals/PausablePortal.sol
contracts/test/examples/portals/PausablePortal.t.sol
contracts/test/mocks/AttestationRegistryMock.sol

Introduces a `PausablePortal` leveraging the `Pausable` contract from OpenZeppeline.
This gives an example of how to create a Portal that can be paused in case of emergency, preventing it from issuing, replacing or revoking any Attestation if needed.
Fixes #712

feat(contracts): As a developer, I want to have a PausablePortal example

---

contracts/src/PortalRegistry.sol
contracts/src/stdlib/IssuersModule.sol
contracts/src/stdlib/IssuersModuleV2.sol
contracts/test/PortalRegistry.t.sol
contracts/test/integration/IssuersPortal.t.sol
contracts/test/integration/IssuersPortalV2.t.sol
contracts/test/stdlib/IssuersModule.t.sol
contracts/test/stdlib/IssuersModuleV2.t.sol

1. Forbids the Zero Address from being registered as an Issuer
2. Reinforces the checks when decoding an address
Fixes #717

fix(contracts): As an an Admin, I want to ensure that Issuer addresses cannot be set as the zero address

---

explorer/src/pages/MyAttestations/index.tsx
explorer/src/pages/Search/components/SearchAttestationsReceived/index.tsx
explorer/src/pages/Search/components/SearchAttestationsReceived/loadAttestationReceivedList.ts

1. Implements the same default ordering logic on 2 more pages: "My Attestations" and "Search Results"
2. Fixes an issue with re-ordering on these pages
Fixes #720

fix(explorer): As a user, I want to have a consistent default sorting logic across all the pages in the explorer

---

explorer/src/config/index.tsx

Starts using the "production endpoints" of The Graph for the Explorer
Fixes #723

chore(explorer): Migrate to The Graph production endpoints

---

explorer/src/utils/searchUtils.ts

This PR fixes the case sensitivity issue with omni search
Address and Long Address searches are made case insensitive
Fixes #721

fix(explorer): The search is case sensitive

---

.github/workflows/explorer-build.yml
.github/workflows/explorer-deploy-preview.yml
.github/workflows/lint.yml
.github/workflows/sdk.yml
.github/workflows/smart-contracts.yml
.github/workflows/subgraph.yml
explorer/package.json
explorer/vite.config.ts
pnpm-lock.yaml
sdk/.graphclient/index.ts
sdk/.graphclientrc.yml
sdk/package.json

Makes the Verax SDK compatible with frontends in multichain mode:
Fixes #746

chore(sdk): Outstanding Issues in Multi-Chain Feature for SDK

---

sdk/examples/portal/portalExamples.ts
sdk/package.json
sdk/src/abi/DefaultPortal.ts
sdk/src/dataMapper/PortalDataMapper.ts

Introduces an `attestV2` function at the SDK level to leverage the new version of the Attestation process.
> [!NOTE]
> This function name is not ideal, and will be renamed to just `attest` once the legacy function is deprecated both at the SDK level and the smart contract level.
Fixes #759

chore(sdk): Add a call to attestV2 at the SDK level

---

.github/workflows/sdk.yml
sdk/.npmignore
sdk/jest.config.js
sdk/package.json
sdk/src/dataMapper/AttestationDataMapper.test.ts
sdk/src/dataMapper/BaseDataMapper.test.ts
sdk/src/dataMapper/ModuleDataMapper.test.ts
sdk/src/dataMapper/PortalDataMapper.test.ts
sdk/src/dataMapper/SchemaDataMapper.test.ts
sdk/src/utils/abiCoder.test.ts
sdk/src/utils/errorHandler.test.ts
sdk/src/utils/graphClientHelper.test.ts
sdk/src/utils/ipfsClient.test.ts
sdk/tsconfig.build.json

Unit tests are added in SDK for utils and base data mapper
Fixes #727

chore(sdk): Add unit tests for the subgraph calls on the SDK

---

.github/workflows/sdk.yml

If the PR is made from the main Verax repository, the SDK coverage report is uploaded to Codecov.
If the PR is made from a forked repository, the SDK coverage is not uploaded to Codecov.
Fixes #767

chore(ci): Upload SDK coverage report only from the main repository

---

contracts/src/AttestationRegistry.sol
contracts/src/examples/portals/EASPortal.sol
contracts/src/stdlib/IndexerModuleV2.sol
contracts/test/AttestationRegistry.t.sol
contracts/test/examples/portals/EASPortal.t.sol
contracts/test/mocks/AttestationRegistryMock.sol
contracts/test/stdlib/IndexerModuleV2.t.sol

It adds chain prefix in attestation id generation logic in the examples where it was missing.
Fixes #787

feat(contracts):  Fix Attestation ID generation in examples

---

contracts/README.md

Correction typos. This makes the document clearer.
"fotge" -> "forge"
"fpr" -> "for"

docs(contracts): Fix typos

---

contracts/.solhint.json
contracts/package.json
contracts/src/AttestationRegistry.sol
contracts/src/PortalRegistry.sol
contracts/src/examples/portals/EASPortal.sol
contracts/src/examples/portals/PausablePortal.sol
contracts/src/stdlib/IndexerModule.sol
contracts/src/stdlib/IndexerModuleV2.sol
contracts/test/PortalRegistry.t.sol
contracts/test/examples/portals/PausablePortal.t.sol
contracts/test/mocks/AttestationRegistryMock.sol
contracts/test/mocks/EASRegistryMock.sol
contracts/test/mocks/PortalRegistryMock.sol
contracts/test/mocks/PortalRegistryNotAllowlistedMock.sol
pnpm-lock.yaml

- Updates Solhint
- Fixes linting issues on the contracts
- Switches unnecessary `memory` to `calldata`
Fixes #811

chore(contracts): Fix lint issues on contracts

---

contracts/src/abstracts/AbstractModule.sol
contracts/src/abstracts/AbstractModuleV2.sol
contracts/src/abstracts/AbstractPortal.sol
contracts/src/abstracts/AbstractPortalV2.sol
contracts/src/examples/portals/NFTPortal.sol
contracts/src/interfaces/IPortal.sol
contracts/test/PortalRegistry.t.sol

Uses inheritance of `ERC165` for better `supportsInterface`
Fixes #817

chore(contracts): supportsInterface should make use of inheritance

---

contracts/src/AttestationReader.sol
contracts/src/AttestationRegistry.sol
contracts/src/ModuleRegistry.sol
contracts/src/PortalRegistry.sol
contracts/src/RouterManager.sol
contracts/src/SchemaRegistry.sol
contracts/test/AttestationReader.t.sol
contracts/test/AttestationRegistry.t.sol
contracts/test/ModuleRegistry.t.sol
contracts/test/PortalRegistry.t.sol
contracts/test/RouterManager.t.sol
contracts/test/SchemaRegistry.t.sol
contracts/test/mocks/RouterManagerTestContract.sol

Introduces a `RouterManger` contract to avoid duplicating this piece of code everywhere
Fixes #819

chore(contracts): Refactor duplicated code to manage the Router address

---

explorer/package.json
explorer/src/components/EnsNameDisplay/index.tsx
explorer/src/config/index.tsx
explorer/src/interfaces/config/index.ts
explorer/src/pages/Attestation/components/AttestationInfo/index.tsx
explorer/src/pages/Portal/index.tsx
explorer/src/providers/index.tsx
explorer/src/providers/network-provider/index.tsx
pnpm-lock.yaml

Updates the Explorer to use [Wagmi](https://wagmi.sh/) & [Viem](https://viem.sh/) v2
Fixes #520

chore(explorer): Update wagmi to v2 in the Explorer

---

contracts/src/AttestationReader.sol
contracts/src/AttestationRegistry.sol
contracts/src/ModuleRegistry.sol
contracts/src/PortalRegistry.sol
contracts/src/SchemaRegistry.sol
contracts/test/AttestationReader.t.sol
contracts/test/AttestationRegistry.t.sol
contracts/test/ModuleRegistry.t.sol
contracts/test/PortalRegistry.t.sol
contracts/test/SchemaRegistry.t.sol

Updated registries with additional check - if there is no change in the state revert the transaction.
Fixes #804

chore(contracts): Revert when no change happens in a state-changing function

---

contracts/test/DefaultPortal.t.sol
contracts/test/DefaultPortalV2.t.sol

Adds a couple of tests to cover the `bulkRevoke` functions and hooks on the Abstract Portals.
Fixes #821

chore(contracts): Add tests to cover the bulkRevoke function in AbstractPortal and AbstractPortalV2

---

contracts/src/SchemaRegistry.sol

Removes the unused onlyPortalRegistry modifier
Fixes #828

chore(contracts): The onlyPortalRegistry modifier is not used in the codebase

---

contracts/src/AttestationRegistry.sol

chore(contracts): Replacing an Attestation should revoke first and create the new attestation later

---

CONTRIBUTING.md

Improves the Contribution doc
Fixes #846

doc: Improve the contribution documentation

---

explorer/src/pages/Home/components/Info/data.tsx

Updates the Explorer's homepage blocks to provide direct access to Verax documentation and website, improving user experience and accessibility to key resources.
- Left block now links directly to the Developer Guide for attestation issuers
- Right block now links to the Verax main landing page
- Resolves #781
1. Visit the Explorer's homepage
2. Verify left block's "Get Started" button links to: https://docs.ver.ax/verax-documentation/developer-guides/for-attestation-issuers
3. Verify right block's "Learn More" button links to: https://ver.ax

As a user, I want to easily access Verax documentation and website

---

explorer/src/components/DataTable/components/TdHandler/index.tsx
explorer/src/components/DataTable/index.tsx
explorer/src/components/Tooltip/index.tsx
explorer/src/pages/Attestation/components/AttestationInfo/index.tsx

Added a tooltip to provide clarity about attestation expiration dates. This enhancement helps users better understand that attestation validity is determined by the issuer and that adherence to expiration dates is optional for consumers.
- Added an information icon (ℹ️) next to the Expiration Date field in attestation details
- Implemented hover tooltip using the existing [Tooltip](cci:1://file:///c:/Users/CHIRAG%20S%20KOTIAN/Desktop/clg%20project/linea-attestation-registry/explorer/src/components/Tooltip/index.tsx:21:0-67:2) component
- Added disclaimer text explaining the nature of attestation validity
- Maintained consistent styling with the application's design system
- Used Lucide React's [Info](cci:1://file:///c:/Users/CHIRAG%20S%20KOTIAN/Desktop/clg%20project/linea-attestation-regis …

feat(explorer): As a User, I want to see a disclaimer on the expiration date

---

README.md

Verax Attestation Registry is a community-led initiative" — the word "lead" is used incorrectly here. It should be replaced with "led," as it refers to an initiative that is "led" by the community, not "conducted" (lead).

Fixing Typo: 'Lead' to 'Led' in 'Community-Led Initiative'"

---

contracts/README.md
contracts/package.json
contracts/script/deploy/deployEas.ts
contracts/script/deploy/deployEverything.ts

- Improves the Contracts documentation
- Better describes the deployment process
Fixes #854

chore(contracts): Document the deployment of a new Verax instance

---

explorer/src/pages/Search/index.tsx
snap/packages/site/package.json
snap/packages/snap/package.json

This PR implements automatic navigation from the search page when attestation-specific results are found. When the search results only contain attestations (no modules, portals, or schemas), the user is automatically redirected to:
- The attestation details page if the search term matches an attestation ID
- The subject's attestations page if the search term matches other attestation criteria
Fixes #872

fix(explorer): Fix attestation ID search redirection

---

contracts/script/deploy/deployEverything.ts
contracts/src/AttestationRegistry.sol
contracts/test/AttestationRegistry.t.sol

chore(contracts): Remove `updateChainPrefix` Function to Prevent Risks

---

contracts/src/ModuleRegistry.sol
contracts/src/PortalRegistry.sol
contracts/src/SchemaRegistry.sol

chore(contracts): Deprecate State Variables in Registries

---

contracts/src/AttestationRegistry.sol
contracts/src/ModuleRegistry.sol
contracts/src/PortalRegistry.sol
contracts/src/SchemaRegistry.sol
contracts/src/abstracts/AbstractModuleV2.sol
contracts/src/examples/modules/ERC712ModuleV2.sol
contracts/src/examples/modules/MerkleProofModuleV2.sol
contracts/src/examples/portals/EASPortal.sol
contracts/src/examples/portals/NFTPortal.sol
contracts/src/stdlib/ECDSAModuleV2.sol
contracts/src/stdlib/ERC1271ModuleV2.sol
contracts/src/stdlib/FeeModuleV2.sol
contracts/src/stdlib/IndexerModuleV2.sol
contracts/src/stdlib/IssuersModuleV2.sol
contracts/src/stdlib/SchemaModuleV2.sol
contracts/src/stdlib/SenderModuleV2.sol
contracts/test/mocks/CorrectModuleV2Mock.sol
contracts/test/mocks/PortalRegistryNotAllowlistedMock.sol

chore(contracts): Frequent Use of `memory` Parameters Where `calldata` Would Be Possible
